### ISSUE TITLE
"Submitter" switch is almost invisible

### ISSUE THREAD

**Issue by pferreir** [indico/indico#3731]
Many users have a hard time figuring out that it's there, thanks to low contrast and sub-standard screens.

![image](https://user-images.githubusercontent.com/2699/51533563-8ab0de80-1e43-11e9-9450-e70e596b6c59.png)

**Comment by selkieupsilon** [comment]
Not sure if this helps -- I was investigating how to recolour the "speakers" switch, which is on a very similar colour scheme. I ended up with something like this:
![screenshot from 2019-02-13 01-48-53](https://user-images.githubusercontent.com/5978543/52678782-2b6e5780-2f33-11e9-8627-c23de5f7972a.png)
![screenshot from 2019-02-13 01-48-59](https://user-images.githubusercontent.com/5978543/52678798-31643880-2f33-11e9-8092-5077458e277a.png)

I did this all by CSS.
```css
.person-link-list .person-buttons:not(.selected) {`
    opacity: .8;
}

.i-label.small.speaker:not(.selected)::after  {
    content: "? (Select at least one)";
}

.person-link-list .person-row .person-roles .i-label:not(.selected) {
    color:#317d85!important;
}

.i-label.speaker.selected {
    color: #fff;
    background-color: #317d85;
}
```

Is this better?

It looks like it should actually be modified in the indico scss code here https://github.com/indico/indico/blob/007c6cc9e5597d1f1adb09ce93970365ff8f7d2f/indico/web/client/styles/widgets/_person_link.scss  though I don't know how to test this.
