### ISSUE TITLE
2 LDAP servers for authorisation indi Indico

### ISSUE THREAD

**Issue by astral0pitek** [indico/indico#6068]
We recently deployed a server with Indico 3.2.8 in our university. We have 2 separate Active Directory authorization servers (one for employees and one for teachers and students).

We were successfully able to connect one of the servers for authorization via LDAP, but when we try to connect the second LDAP server, the error “There can only be one sync provider” appears.

Is it even possible to add 2 servers so that you can choose which of the two servers to log into indico?

The configuration for which we are unable to add 2 authorization servers:

```yaml
AUTH_PROVIDERS = {
    'ldap_1': {
        'type': 'ldap',
        'title': 'LDAP_1',
        'ldap': _ldap_1_config,
        'default': True
    },
    'ldap_2': {
        'type': 'ldap',
        'title': 'LDAP_2',
        'ldap': _ldap_2_config,
        'default': False
    }
}

IDENTITY_PROVIDERS = {
    'ldap_1': {
        'type': 'ldap',
        'title': 'LDAP_1',
        'ldap': _ldap_1_config,
        'mapping': {
            'first_name': 'givenName',
            'last_name': 'sn',
            'email': 'mail',
            'affiliation': 'company',
            'phone': 'telephoneNumber'
        },
        'trusted_email': True,
        'synced_fields': {'first_name', 'last_name', 'affiliation', 'phone', 'address'}
    },
    'ldap_2': {
        'type': 'ldap',
        'title': 'LDAP_2',
        'ldap': _ldap_2_config,
        'mapping': {
            'first_name': 'givenName',
            'last_name': 'sn',
            'email': 'mail',
            'affiliation': 'company',
            'phone': 'telephoneNumber'
        },
        'trusted_email': True,
        'synced_fields': {'first_name', 'last_name', 'affiliation', 'phone', 'address'}
    }
}

PROVIDER_MAP = {
    'ldap_1': 'ldap_1',
    'ldap_2': 'ldap_2'
}
```
